name: Build and Deploy Docker Image

on:
  push:
    branches: [ main, master ]  # 根据您的主分支名称调整
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整历史记录
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: swr.cn-north-4.myhuaweicloud.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/moneyprinterplus:latest
        build-args: |
          CACHE_DATE=${{ github.run_id }}-${{ github.run_number }}-${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        no-cache: true  # 禁用缓存，确保每次都重新构建
